version: "3.8"

services:
  curricurum_react-to-go:
    container_name: curriculum_react-to-go
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: curriculum_react-to-go
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

volumes:
  curriculum_react-to-go:
    name: curriculum_react-to-go