version: "3.8"

services:
  hack:
    container_name: hack
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: hack
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

volumes:
  hack:
    name: hack